"""Translating design tokens into the files each component actually reads.

Hyprland wants Lua, Waybar wants JSONC and GTK3 CSS, Quickshell wants
JSON. None of them derive anything themselves — everything here is a
projection of the token document from `halcyon.theme`, so the three
surfaces cannot drift apart.

Every file is written atomically and carries a "do not edit" banner
pointing at the setting that produced it.
"""

from __future__ import annotations

import json
import os
import shutil
import tempfile
from typing import Any, Iterable

from . import hyprland, paths


class RenderError(RuntimeError):
    """Raised when a generated file would be invalid for this Hyprland."""


BANNER = (
    "Generated by Halcyon — do not edit.\n"
    "Change settings.json (or use the Settings app) and run `halcyon theme apply`."
)

# ── Animation presets ──────────────────────────────────────────────────
#
# Leaf names come straight from Hyprland's animation tree; the curve
# names are declared by `hl.curve` in the generated file. `style` is the
# per-leaf animation style Hyprland documents for that node.

_SPRING = "halcyonSpring"
_SOFT = "halcyonSoft"

#: (duration-token, curve, style, spring?)
_MACOS = {
    "global":              ("standard",   "standard",   None,                 False),
    "windows":             ("standard",   "emphasised", None,                 True),
    "windowsIn":           ("emphasised", "emphasised", "popin 92%",          True),
    "windowsOut":          ("quick",      "accelerate", "popin 94%",          False),
    "windowsMove":         ("standard",   "standard",   None,                 True),
    "border":              ("quick",      "gentle",     None,                 False),
    "borderangle":         (None,         None,         None,                 False),
    "shadowangle":         (None,         None,         None,                 False),
    "glowangle":           (None,         None,         None,                 False),
    "fade":                ("quick",      "gentle",     None,                 False),
    "fadeIn":              ("quick",      "decelerate", None,                 False),
    "fadeOut":             ("instant",    "accelerate", None,                 False),
    "fadeSwitch":          ("quick",      "gentle",     None,                 False),
    "fadeShadow":          ("quick",      "gentle",     None,                 False),
    "fadeGlow":            ("quick",      "gentle",     None,                 False),
    "fadeDim":             ("standard",   "gentle",     None,                 False),
    "fadeDpms":            ("standard",   "gentle",     None,                 False),
    "fadeLayers":          ("quick",      "gentle",     None,                 False),
    "fadeLayersIn":        ("overlay",    "decelerate", None,                 False),
    "fadeLayersOut":       ("quick",      "accelerate", None,                 False),
    "fadePopups":          ("instant",    "decelerate", None,                 False),
    "fadePopupsIn":        ("instant",    "decelerate", None,                 False),
    "fadePopupsOut":       ("instant",    "accelerate", None,                 False),
    "layers":              ("overlay",    "emphasised", "fade",               False),
    "layersIn":            ("overlay",    "decelerate", "fade",               False),
    "layersOut":           ("quick",      "accelerate", "fade",               False),
    "workspaces":          ("workspace",  "emphasised", "slidefade 15%",      False),
    "workspacesIn":        ("workspace",  "emphasised", "slidefade 15%",      False),
    "workspacesOut":       ("workspace",  "emphasised", "slidefade 15%",      False),
    "specialWorkspace":    ("overlay",    "emphasised", "slidefadevert 20%",  False),
    "specialWorkspaceIn":  ("overlay",    "decelerate", "slidefadevert 20%",  False),
    "specialWorkspaceOut": ("quick",      "accelerate", "slidefadevert 20%",  False),
    "zoomFactor":          ("quick",      "decelerate", None,                 False),
    "monitorAdded":        ("standard",   "decelerate", None,                 False),
}


def _preset_overrides(name: str) -> dict[str, tuple[Any, ...]]:
    """Presets are deltas on the macOS table, not separate tables.

    Keeping one table and overlaying differences means a new animation
    leaf gets sensible behaviour in every preset at once.
    """
    if name == "minimal":
        return {
            "windowsIn": ("quick", "decelerate", "popin 96%", False),
            "windowsOut": ("instant", "accelerate", "popin 96%", False),
            "windows": ("quick", "standard", None, False),
            "windowsMove": ("quick", "standard", None, False),
            "workspaces": ("quick", "standard", "fade", False),
            "workspacesIn": ("quick", "standard", "fade", False),
            "workspacesOut": ("quick", "standard", "fade", False),
            "specialWorkspace": ("quick", "standard", "fade", False),
            "specialWorkspaceIn": ("quick", "standard", "fade", False),
            "specialWorkspaceOut": ("quick", "standard", "fade", False),
            "layers": ("quick", "standard", "fade", False),
            "layersIn": ("quick", "standard", "fade", False),
            "layersOut": ("instant", "accelerate", "fade", False),
        }
    if name == "fast":
        return {
            "windowsIn": ("quick", "decelerate", "popin 94%", False),
            "windowsOut": ("instant", "accelerate", "popin 94%", False),
            "windows": ("quick", "standard", None, False),
            "windowsMove": ("quick", "standard", None, False),
            "workspaces": ("quick", "accelerate", "slide", False),
            "workspacesIn": ("quick", "accelerate", "slide", False),
            "workspacesOut": ("quick", "accelerate", "slide", False),
        }
    if name == "smooth":
        return {
            "windowsIn": ("slow", "emphasised", "popin 88%", True),
            "windowsOut": ("standard", "accelerate", "popin 90%", False),
            "windowsMove": ("emphasised", "emphasised", None, True),
            "workspaces": ("slow", "emphasised", "slidefade 20%", False),
            "workspacesIn": ("slow", "emphasised", "slidefade 20%", False),
            "workspacesOut": ("slow", "emphasised", "slidefade 20%", False),
            "layersIn": ("emphasised", "decelerate", "fade", False),
        }
    return {}


CURVE_NAMES = {
    "standard": "halcyonStandard",
    "decelerate": "halcyonDecel",
    "accelerate": "halcyonAccel",
    "emphasised": "halcyonEmphasis",
    "gentle": "halcyonGentle",
    "overshoot": "halcyonOvershoot",
    "linear": "halcyonLinear",
}


# ── Lua helpers ────────────────────────────────────────────────────────


def lua_string(value: str) -> str:
    """Quote a Lua string literal safely.

    Generated files contain user-supplied text (font names, commands,
    workspace names), so this has to be correct rather than convenient.
    """
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def lua_value(value: Any, indent: int = 0) -> str:
    pad = "    " * indent
    inner = "    " * (indent + 1)
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "nil"
    if isinstance(value, (int, float)):
        if isinstance(value, float) and value == int(value):
            return str(int(value))
        return repr(value)
    if isinstance(value, str):
        return lua_string(value)
    if isinstance(value, (list, tuple)):
        if not value:
            return "{}"
        items = ",\n".join(f"{inner}{lua_value(item, indent + 1)}" for item in value)
        return "{\n" + items + f",\n{pad}}}"
    if isinstance(value, dict):
        if not value:
            return "{}"
        lines = []
        for key, item in value.items():
            key_text = (
                str(key)
                if str(key).isidentifier()
                else f"[{lua_string(str(key))}]"
            )
            lines.append(f"{inner}{key_text} = {lua_value(item, indent + 1)}")
        return "{\n" + ",\n".join(lines) + f",\n{pad}}}"
    raise TypeError(f"Cannot express {type(value).__name__} in Lua")


def _lua_banner() -> str:
    return "".join(f"-- {line}\n" for line in BANNER.splitlines())


def write_atomic(path: os.PathLike[str] | str, content: str) -> None:
    path = str(path)
    directory = os.path.dirname(path) or "."
    os.makedirs(directory, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=directory, prefix=".halcyon-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


# ── theme.json (Quickshell) ────────────────────────────────────────────


def render_theme_json(tokens: dict[str, Any]) -> str:
    return json.dumps(tokens, indent=2, sort_keys=False) + "\n"


# ── Waybar colours (GTK3 CSS) ──────────────────────────────────────────

#: Waybar runs on GTK3, whose CSS has no custom properties — but it does
#: support `@define-color`, which is what we generate.
_WAYBAR_COLOR_KEYS = [
    "accent", "accentText", "accentHover", "accentPressed", "onAccent",
    "secondary", "tertiary",
    "text", "textSecondary", "textTertiary", "textDisabled",
    "surface", "surfaceRaised", "surfaceSunken", "surfaceHover",
    "surfacePressed", "surfaceSelected", "surfaceSolid",
    "glassTint", "glassHighlight", "glassBorder", "glassBorderStrong",
    "separator", "shadow", "scrim", "backdrop",
    "workspaceActive", "workspaceOccupied", "workspaceIdle",
    "success", "warning", "danger", "info",
]


def _argb_to_css(value: str) -> str:
    """`#AARRGGBB` → `rgba(r, g, b, a)`, which GTK3 understands."""
    raw = value.lstrip("#")
    if len(raw) == 8:
        a, r, g, b = (int(raw[i:i + 2], 16) for i in (0, 2, 4, 6))
    elif len(raw) == 6:
        a = 255
        r, g, b = (int(raw[i:i + 2], 16) for i in (0, 2, 4))
    else:
        return value
    return f"rgba({r}, {g}, {b}, {a / 255:.3f})"


def render_waybar_css(tokens: dict[str, Any]) -> str:
    colors = tokens["color"]
    typography = tokens["typography"]
    bar = tokens["bar"]
    radius = tokens["radius"]
    spacing = tokens["spacing"]
    motion = tokens["motion"]

    lines = [f"/* {line} */" for line in BANNER.splitlines()]
    lines.append("")
    for key in _WAYBAR_COLOR_KEYS:
        if key in colors:
            lines.append(f"@define-color hal-{_kebab(key)} {_argb_to_css(colors[key])};")

    # GTK3 has no variables beyond colours, so numeric tokens are emitted
    # as a small set of utility rules the static stylesheet composes with.
    lines += [
        "",
        "/* Metrics — GTK3 CSS has no custom properties, so the numbers the",
        "   theme controls land here as concrete rules. */",
        "",
        "window#waybar {",
        f"  font-family: \"{typography['family']}\", sans-serif;",
        f"  font-size: {typography['size']['body']}px;",
        "}",
        "",
        ".hal-pill {",
        f"  border-radius: {radius['md']}px;",
        f"  padding: 0 {spacing['sm']}px;",
        f"  margin: {max(2, bar['topMargin'] // 2)}px {spacing['xxs']}px;",
        "}",
        "",
        ".hal-group {",
        f"  border-radius: {radius['lg']}px;",
        f"  padding: 0 {spacing['xs']}px;",
        "}",
        "",
        ".hal-transition {",
        f"  transition: background-color {motion['duration']['quick']}ms ease,",
        f"              color {motion['duration']['quick']}ms ease;",
        "}",
        "",
    ]
    return "\n".join(lines) + "\n"


def _kebab(name: str) -> str:
    out: list[str] = []
    for index, char in enumerate(name):
        if char.isupper() and index:
            out.append("-")
        out.append(char.lower())
    return "".join(out)


# ── Hyprland: theme ────────────────────────────────────────────────────


def render_hypr_theme_lua(tokens: dict[str, Any], settings: dict[str, Any]) -> str:
    colors = tokens["color"]
    glass = tokens["glass"]
    blur = tokens["blur"]
    shadow = tokens["shadow"]
    radius = tokens["radius"]
    graphics = settings.get("graphics", {})
    workspaces = settings.get("workspaces", {})

    gaps_in = int(round(glass["widgetSpacing"] * 0.6))
    gaps_out = int(round(glass["panelPadding"] * 1.15))

    table = {
        "mode": tokens["mode"],
        "accent": _argb_to_hypr(colors["accent"]),
        "borderActive": _argb_to_hypr(colors["borderActive"]),
        "borderActiveEnd": _argb_to_hypr(colors["borderActiveEnd"]),
        "borderInactive": _argb_to_hypr(colors["borderInactive"]),
        "shadowColor": _argb_to_hypr(colors["shadow"]),
        "background": _argb_to_hypr(colors["backdrop"]),
        "rounding": int(radius["window"]),
        "roundingPower": float(radius["power"]),
        "borderSize": 2 if tokens["accessibility"]["highContrast"] else 1,
        "gapsIn": gaps_in,
        "gapsOut": gaps_out,
        "gapsWorkspaces": 0,
        "activeOpacity": 1.0,
        "inactiveOpacity": round(
            1.0 - (1.0 - float(graphics.get("transparency", 1.0))) * 0.0, 3
        ),
        "blur": {
            "enabled": bool(blur["enabled"]),
            "size": int(blur["size"]),
            "passes": int(blur["passes"]),
            "newOptimizations": bool(blur["newOptimizations"]),
            "xray": bool(blur["xray"]),
            "vibrancy": round(0.08 + glass["saturation"] * 0.09, 4),
            "vibrancyDarkness": round(glass["refraction"] * 0.2, 4),
            "noise": round(glass["noise"], 5),
            "brightness": round(1.0 + (0.04 if tokens["mode"] == "light" else -0.02), 4),
            "contrast": round(0.82 + glass["saturation"] * 0.08, 4),
            "special": False,
            "popups": True,
            "popupsIgnoreAlpha": 0.35,
            "ignoreOpacity": True,
        },
        "shadow": {
            "enabled": bool(shadow["enabled"]),
            "range": int(shadow["range"]),
            "renderPower": int(shadow["renderPower"]),
            "scale": round(0.9, 3),
            "sharp": False,
        },
        "smartGaps": bool(workspaces.get("smartGaps", True)),
        "renderUnfocusedFps": int(graphics.get("renderUnfocusedFps", 10)),
        "font": tokens["typography"]["family"],
        "cursorTheme": settings.get("appearance", {}).get("cursorTheme", ""),
        "cursorSize": int(settings.get("appearance", {}).get("cursorSize", 24)),
    }

    return (
        _lua_banner()
        + "\n---@class HalcyonTheme\nreturn "
        + lua_value(table)
        + "\n"
    )


def _argb_to_hypr(value: str) -> str:
    """`#AARRGGBB` → Hyprland's `rgba(RRGGBBAA)` string form."""
    raw = value.lstrip("#")
    if len(raw) == 8:
        return f"rgba({raw[2:]}{raw[0:2]})"
    if len(raw) == 6:
        return f"rgba({raw}ff)"
    return value


# ── Hyprland: animations ───────────────────────────────────────────────


def render_hypr_animations_lua(tokens: dict[str, Any]) -> str:
    motion = tokens["motion"]
    preset = motion["preset"]
    table = dict(_MACOS)
    table.update(_preset_overrides(preset))

    out: list[str] = [_lua_banner(), ""]
    out.append("local hl = hl\n")
    out.append("-- Shared easing curves. QML uses the same control points so an\n")
    out.append("-- overlay fading in over a window matches the window's own motion.\n")
    for key, control in motion["curve"].items():
        name = CURVE_NAMES.get(key)
        if not name:
            continue
        x1, y1, x2, y2 = control
        out.append(
            f'hl.curve({lua_string(name)}, {{ type = "bezier", '
            f"points = {{ {{{x1}, {y1}}}, {{{x2}, {y2}}} }} }})\n"
        )

    if motion["springs"]:
        out.append("\n-- Springs carry the weight of window motion; stiffness sets the\n")
        out.append("-- speed and dampening removes the bounce.\n")
        out.append(
            f'hl.curve({lua_string(_SPRING)}, {{ type = "spring", '
            "mass = 1, stiffness = 244, dampening = 25.5 })\n"
        )
        out.append(
            f'hl.curve({lua_string(_SOFT)}, {{ type = "spring", '
            "mass = 1, stiffness = 168, dampening = 24 })\n"
        )

    out.append("\nhl.config({ animations = { enabled = ")
    out.append("false" if motion["disabled"] else "true")
    out.append(", workspace_wraparound = false } })\n\n")

    if motion["disabled"]:
        out.append("-- Animations are switched off; nothing further to declare.\n")
        return "".join(out)

    durations = motion["duration"]
    for leaf, spec in table.items():
        duration_key, curve_key, style, use_spring = spec
        if duration_key is None:
            # Continuously-animating leaves (gradient angles) stay off:
            # they redraw every frame forever and cost real battery.
            out.append(
                f'hl.animation({{ leaf = {lua_string(leaf)}, enabled = false }})\n'
            )
            continue

        ms = durations.get(duration_key, durations["standard"])
        speed = max(0.1, round(ms / 100.0, 2))
        parts = [f"leaf = {lua_string(leaf)}", "enabled = true", f"speed = {speed}"]
        if use_spring and motion["springs"]:
            parts.append(f"spring = {lua_string(_SPRING)}")
        else:
            parts.append(f"bezier = {lua_string(CURVE_NAMES[curve_key])}")
        if style:
            parts.append(f"style = {lua_string(style)}")
        out.append("hl.animation({ " + ", ".join(parts) + " })\n")

    return "".join(out)


# ── Hyprland: keybinds ─────────────────────────────────────────────────


class KeybindError(ValueError):
    """A catalog entry that cannot be turned into a safe binding."""


def halcyon_binary() -> str:
    """The `halcyon` launcher, as an absolute path where we can find one.

    Hyprland runs `exec_cmd` through /bin/sh, which inherits the session's
    PATH — and ~/.local/bin is missing from it often enough that baking the
    resolved path into the generated file is the difference between binds
    that work and binds that silently do nothing. The file is regenerated
    on every `theme apply`, so nothing goes stale.
    """
    found = shutil.which("halcyon")
    if found:
        return found
    local = os.path.expanduser("~/.local/bin/halcyon")
    if os.path.isfile(local) and os.access(local, os.X_OK):
        return local
    return "halcyon"


def render_hypr_keybinds_lua(
    settings: dict[str, Any], catalog: dict[str, Any]
) -> str:
    overrides = settings.get("keybinds") or {}
    binary = halcyon_binary()
    workspaces = settings.get("workspaces", {})
    count = max(1, min(20, int(workspaces.get("count", 10))))

    out: list[str] = [_lua_banner(), "\nlocal hl = hl\n\n"]
    out.append("-- Bindings come from settings.json layered over the shipped\n")
    out.append("-- catalog, so the Settings app can rebind anything without a\n")
    out.append("-- human editing Lua.\n\n")

    seen: dict[str, str] = {}
    for entry in catalog.get("binds", []):
        bind_id = entry["id"]
        binding = str(overrides.get(bind_id, entry.get("default", ""))).strip()
        if not binding or binding.lower() in ("none", "unbound", "disabled"):
            continue

        normalised = binding.upper().replace(" ", "")
        if normalised in seen:
            out.append(
                f"-- skipped {bind_id}: {binding} is already bound to "
                f"{seen[normalised]}\n"
            )
            continue
        seen[normalised] = bind_id

        action = _bind_action(entry, binary)
        options = _bind_options(entry)
        suffix = f", {options}" if options else ""
        out.append(f"hl.bind({lua_string(binding)}, {action}{suffix})\n")

    # Workspace binds are generated here rather than as a Lua loop so they
    # go through the same duplicate check as everything else — which is
    # how the collision with the macOS capture shortcuts was found.
    #
    # Super+Shift+<n> is the usual Linux "move window to workspace", but
    # Super+Shift+3/4/5 are the macOS screenshot shortcuts this desktop
    # deliberately keeps. Rather than splitting the digits across two
    # modifiers, every move-to-workspace bind uses Super+Ctrl.
    out.append("\n-- Workspaces. Super switches, Super+Ctrl moves the window.\n")
    out.append("-- Super+Shift+<digit> is left to the macOS capture shortcuts.\n")
    for index in range(1, min(count, 10) + 1):
        key = index % 10
        for modifier, expression, label in (
            ("SUPER", f"hl.dsp.focus({{ workspace = {index} }})", f"Workspace {index}"),
            (
                "SUPER + CTRL",
                f"hl.dsp.window.move({{ workspace = {index}, follow = true }})",
                f"Move window to workspace {index}",
            ),
        ):
            binding = f"{modifier} + {key}"
            normalised = binding.upper().replace(" ", "")
            if normalised in seen:
                out.append(
                    f"-- skipped {label}: {binding} is already bound to "
                    f"{seen[normalised]}\n"
                )
                continue
            seen[normalised] = label
            out.append(
                f"hl.bind({lua_string(binding)}, {expression}, "
                f"{{ description = {lua_string(label)} }})\n"
            )
    out.append("\n")

    for entry in catalog.get("mouseBinds", []):
        binding = str(overrides.get(entry["id"], entry.get("default", ""))).strip()
        if not binding:
            continue
        action = _bind_action(entry, binary)
        out.append(f"hl.bind({lua_string(binding)}, {action}, {{ mouse = true }})\n")

    out.append(
        '\nhl.bind("SUPER + SHIFT + mouse_down", hl.dsp.focus({ workspace = "e+1" }))\n'
    )
    out.append(
        'hl.bind("SUPER + SHIFT + mouse_up", hl.dsp.focus({ workspace = "e-1" }))\n'
    )
    return "".join(out)


def _bind_action(entry: dict[str, Any], binary: str = "halcyon") -> str:
    run = entry.get("run") or {}
    if "exec" in run:
        command = str(run["exec"])
        if command == "halcyon" or command.startswith("halcyon "):
            command = binary + command[len("halcyon"):]
        return f"hl.dsp.exec_cmd({lua_string(command)})"
    if "dsp" in run:
        expression = str(run["dsp"]).strip()
        # The catalog is shipped data, but it is still data: only allow
        # it to name a dispatcher, never arbitrary Lua.
        if not expression.startswith("hl.dsp."):
            raise KeybindError(
                f"{entry.get('id')}: dispatcher must start with 'hl.dsp.', "
                f"got {expression!r}"
            )
        return expression
    raise KeybindError(f"{entry.get('id')}: no 'exec' or 'dsp' action")


_BIND_FLAGS = ("repeating", "locked", "release", "non_consuming", "long_press", "mouse")


def _bind_options(entry: dict[str, Any]) -> str:
    flags = entry.get("flags") or {}
    parts = [
        f"{name} = {'true' if flags[name] else 'false'}"
        for name in _BIND_FLAGS
        if name in flags
    ]
    title = entry.get("title")
    if title:
        parts.append(f"description = {lua_string(str(title))}")
    return "{ " + ", ".join(parts) + " }" if parts else ""


# ── Hyprland: runtime (input, monitors, rules, workspaces) ─────────────


def render_hypr_runtime_lua(
    settings: dict[str, Any], tokens: dict[str, Any], environment: dict[str, str]
) -> str:
    inp = settings.get("input", {})
    displays = settings.get("displays", {})
    workspaces = settings.get("workspaces", {})
    power = settings.get("power", {})
    graphics = settings.get("graphics", {})

    out: list[str] = [_lua_banner(), "\nlocal hl = hl\n\n"]

    out.append("-- Environment. Detected at install time from the hardware that\n")
    out.append("-- is actually present, never applied blindly.\n")
    for key, value in environment.items():
        out.append(f"hl.env({lua_string(key)}, {lua_string(str(value))})\n")

    out.append("\nhl.config(")
    config = {
        "input": {
            "kb_layout": str(inp.get("keyboardLayout", "us")),
            "kb_variant": str(inp.get("keyboardVariant", "")),
            "kb_options": str(inp.get("keyboardOptions", "")),
            "repeat_rate": int(inp.get("repeatRate", 35)),
            "repeat_delay": int(inp.get("repeatDelay", 280)),
            "follow_mouse": int(inp.get("followMouse", 1)),
            "sensitivity": float(inp.get("sensitivity", 0.0)),
            "accel_profile": str(inp.get("accelProfile", "adaptive")),
            "natural_scroll": bool(inp.get("naturalScroll", True)),
            "scroll_factor": float(inp.get("scrollFactor", 1.0)),
            "touchpad": {
                "natural_scroll": bool(inp.get("touchpadNaturalScroll", True)),
                "tap_to_click": bool(inp.get("tapToClick", True)),
                "disable_while_typing": bool(inp.get("disableWhileTyping", True)),
                "tap_and_drag": True,
                "drag_lock": True,
            },
        },
        "general": {
            "allow_tearing": bool(displays.get("allowTearing", False)),
        },
        "misc": {
            "vrr": int(displays.get("vrr", 1)),
            "render_unfocused_fps": int(graphics.get("renderUnfocusedFps", 10)),
            "focus_on_activate": True,
            "animate_manual_resizes": not tokens["motion"]["disabled"],
            "animate_mouse_windowdragging": False,
            "disable_hyprland_logo": True,
            "disable_splash_rendering": True,
            "force_default_wallpaper": 0,
            "background_color": _argb_to_hypr(tokens["color"]["backdrop"]),
        },
        "cursor": {
            "inactive_timeout": 5,
            "hide_on_key_press": False,
            "no_hardware_cursors": 2,
            "warp_on_change_workspace": 2,
        },
        "binds": {
            "workspace_back_and_forth": True,
            "allow_workspace_cycles": True,
            "movefocus_cycles_fullscreen": False,
            "hide_special_on_workspace_change": True,
        },
        "dwindle": {
            "preserve_split": True,
            "smart_split": False,
            "smart_resizing": True,
            "default_split_ratio": 1.0,
        },
        "master": {"new_status": "master", "mfact": 0.55},
    }
    # Refuse to emit an option Hyprland does not have, or a number outside
    # its documented range: a config error here costs the user a broken
    # session, and we can see it coming.
    problems = hyprland.validate_options(config)
    if problems:
        raise RenderError(
            "Generated Hyprland config would be invalid:\n  - "
            + "\n  - ".join(problems)
        )

    out.append(lua_value(config))
    out.append(")\n\n")

    swipe_fingers = int(inp.get("swipeFingers", 3))
    if inp.get("workspaceSwipe", True):
        out.append("-- Three-finger swipe moves between workspaces, matching the\n")
        out.append("-- gesture people arrive from macOS expecting.\n")
        out.append(
            "hl.gesture({ fingers = "
            f"{swipe_fingers}, direction = \"horizontal\", action = \"workspace\" }})\n\n"
        )

    monitors = displays.get("monitors") or []
    if monitors:
        out.append("-- Configured displays.\n")
        for monitor in monitors:
            spec = {
                "output": str(monitor.get("output", "")),
                "mode": str(monitor.get("mode", "preferred")),
                "position": str(monitor.get("position", "auto")),
                "scale": monitor.get("scale", "auto"),
            }
            for optional in ("transform", "vrr", "bitdepth", "mirror", "disabled"):
                if optional in monitor:
                    spec[optional] = monitor[optional]
            out.append(f"hl.monitor({lua_value(spec)})\n")
    else:
        out.append("-- No displays configured: accept whatever is plugged in.\n")
        out.append(
            'hl.monitor({ output = "", mode = "preferred", position = "auto", '
            f'scale = {lua_string(str(displays.get("defaultScale", "auto")))} }})\n'
        )
    out.append("\n")

    out.append(_workspace_rules(workspaces))
    out.append(_window_rules(tokens, power))
    out.append(_layer_rules(tokens))
    return "".join(out)


def _workspace_rules(workspaces: dict[str, Any]) -> str:
    count = max(1, min(20, int(workspaces.get("count", 10))))
    names = workspaces.get("names") or {}
    persistent = bool(workspaces.get("persistent", True))
    smart_gaps = bool(workspaces.get("smartGaps", True))

    out = ["-- Workspaces behave like macOS Spaces: they exist before you\n"]
    out.append("-- visit them, and they keep their name and monitor.\n")
    for index in range(1, count + 1):
        rule: dict[str, Any] = {
            "workspace": str(index),
            "persistent": persistent,
        }
        label = names.get(str(index)) or names.get(index)
        if label:
            rule["default_name"] = str(label)
        if index == 1:
            rule["default"] = True
        out.append(f"hl.workspace_rule({lua_value(rule)})\n")

    if smart_gaps:
        out.append("\n-- No gaps or rounding when a workspace holds a single tiled\n")
        out.append("-- window, so a maximised editor fills the screen cleanly.\n")
        out.append('hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })\n')
        out.append('hl.workspace_rule({ workspace = "f[1]", gaps_out = 0, gaps_in = 0 })\n')
        out.append(
            'hl.window_rule({ name = "halcyon-solo-tiled", '
            'match = { float = false, workspace = "w[tv1]" }, '
            "border_size = 0, rounding = 0 })\n"
        )
        out.append(
            'hl.window_rule({ name = "halcyon-solo-fullscreen", '
            'match = { float = false, workspace = "f[1]" }, '
            "border_size = 0, rounding = 0 })\n"
        )
    out.append("\n")
    return "".join(out)


def _window_rules(tokens: dict[str, Any], power: dict[str, Any]) -> str:
    out = ["-- Window rules.\n"]
    rules: list[dict[str, Any]] = [
        {
            "name": "halcyon-suppress-maximize",
            "match": {"class": ".*"},
            "suppress_event": "maximize",
        },
        {
            "name": "halcyon-fix-xwayland-drag",
            "match": {
                "class": "^$",
                "title": "^$",
                "xwayland": True,
                "float": True,
                "fullscreen": False,
                "pin": False,
            },
            "no_focus": True,
        },
        {
            "name": "halcyon-float-dialogs",
            "match": {"title": "^(Open|Save|Save As|Select|Choose)( File| Folder)?.*$"},
            "float": True,
            "center": True,
        },
        {
            "name": "halcyon-float-pickers",
            "match": {"class": "^(xdg-desktop-portal-gtk|org\\.freedesktop\\.impl\\.portal\\.desktop\\..*)$"},
            "float": True,
            "center": True,
        },
        {
            "name": "halcyon-float-calculator",
            "match": {"class": "^(galculator|gnome-calculator|org\\.gnome\\.Calculator)$"},
            "float": True,
            "size": "420 560",
        },
        {
            "name": "halcyon-picture-in-picture",
            "match": {"title": "^(Picture-in-Picture|Picture in picture)$"},
            "float": True,
            "pin": True,
            "size": "480 270",
            "move": "100%-500 100%-320",
            "no_border": True,
        },
        {
            "name": "halcyon-opaque-media",
            "match": {"class": "^(mpv|vlc|com\\.obsproject\\.Studio|steam_app_.*)$"},
            "opaque": True,
            "no_blur": True,
        },
        {
            "name": "halcyon-immediate-games",
            "match": {"class": "^(steam_app_.*|gamescope|lutris)$"},
            "immediate": True,
            "no_blur": True,
            "opaque": True,
        },
    ]

    if tokens["quality"]["lowPower"]:
        rules.append(
            {
                "name": "halcyon-low-power-no-blur",
                "match": {"float": True},
                "no_blur": True,
            }
        )

    if int(power.get("refreshIntervals", {}).get("batterySeconds", 15)) > 0:
        rules.append(
            {
                "name": "halcyon-render-unfocused-media",
                "match": {"class": "^(mpv|vlc|firefox|zen|chromium|google-chrome)$"},
                "render_unfocused": True,
            }
        )

    for rule in rules:
        out.append(f"hl.window_rule({lua_value(rule)})\n")
    out.append("\n")
    return "".join(out)


def _layer_rules(tokens: dict[str, Any]) -> str:
    """Blur behind the shell's own layers — this is what makes the glass.

    `ignore_alpha` stops the fully transparent parts of an overlay from
    being blurred, which is both a correctness fix (no halo around a
    floating panel) and a large saving on fill rate.
    """
    blur_enabled = bool(tokens["blur"]["enabled"])
    namespaces = [
        ("halcyon-bar", 0.16),
        ("halcyon-overlay", 0.1),
        ("halcyon-spotlight", 0.06),
        ("halcyon-control", 0.1),
        ("halcyon-assistant", 0.06),
        ("halcyon-notifications", 0.14),
        ("halcyon-osd", 0.14),
        ("halcyon-overview", 0.04),
        ("halcyon-switcher", 0.08),
        ("halcyon-dashboard", 0.1),
        ("waybar", 0.16),
    ]

    out = ["-- Layer rules: the shell's surfaces are what get the real blur.\n"]
    for namespace, ignore_alpha in namespaces:
        rule: dict[str, Any] = {
            "name": f"halcyon-layer-{namespace}",
            "match": {"namespace": f"^{namespace}$"},
            "blur": blur_enabled,
            "xray": bool(tokens["blur"]["xray"]),
        }
        if blur_enabled:
            rule["ignore_alpha"] = ignore_alpha
        out.append(f"hl.layer_rule({lua_value(rule)})\n")

    out.append(
        'hl.layer_rule({ name = "halcyon-layer-lock", '
        'match = { namespace = "^halcyon-lock$" }, above_lock = 1, no_screen_share = true })\n'
    )
    out.append("\n")
    return "".join(out)


# ── Waybar configuration ───────────────────────────────────────────────


def render_waybar_config(
    settings: dict[str, Any], tokens: dict[str, Any], base: dict[str, Any]
) -> str:
    """Merge the shipped Waybar module definitions with the user's layout."""
    bar = settings.get("bar", {})
    power_refresh = settings.get("power", {}).get("refreshIntervals", {})
    interval = int(power_refresh.get("acSeconds", 5))

    config = dict(base)
    config["layer"] = "top"
    config["position"] = bar.get("position", "top")
    config["height"] = int(bar.get("height", 34))
    config["spacing"] = tokens["spacing"]["xs"]
    config["margin-top"] = int(bar.get("topMargin", 6)) if bar.get("floating", True) else 0
    config["margin-left"] = int(bar.get("sideMargin", 10)) if bar.get("floating", True) else 0
    config["margin-right"] = config["margin-left"]
    config["modules-left"] = list(bar.get("left", []))
    config["modules-center"] = list(bar.get("center", []))
    config["modules-right"] = list(bar.get("right", []))
    if not bar.get("showOnAllMonitors", True):
        config["output"] = ["!*"]

    # Polling intervals follow the power settings so a laptop on battery
    # is not woken five times a second to redraw a CPU percentage.
    for module in ("cpu", "memory", "temperature", "disk"):
        if module in config and isinstance(config[module], dict):
            config[module]["interval"] = max(1, interval)
    if "custom/gpu" in config:
        config["custom/gpu"]["interval"] = max(2, interval * 2)
    if "custom/hypernix" in config:
        config["custom/hypernix"]["interval"] = max(
            10, int(settings.get("hypernix", {}).get("pollSeconds", 60))
        )

    if not settings.get("hypernix", {}).get("enabled", True):
        for key in ("modules-left", "modules-center", "modules-right"):
            config[key] = [m for m in config[key] if m != "custom/hypernix"]
    if not settings.get("assistant", {}).get("enabled", True):
        for key in ("modules-left", "modules-center", "modules-right"):
            config[key] = [m for m in config[key] if m != "custom/assistant"]

    used = set(config["modules-left"] + config["modules-center"] + config["modules-right"])
    for key in list(config):
        if ("/" in key or key in _WAYBAR_BUILTIN) and key not in used:
            # Waybar instantiates every module it finds a definition for,
            # so leaving unused ones in place costs real CPU.
            del config[key]

    _resolve_waybar_commands(config, halcyon_binary())

    header = "\n".join(f"// {line}" for line in BANNER.splitlines())
    return header + "\n" + json.dumps(config, indent=2) + "\n"


#: Module fields Waybar executes as shell commands.
_WAYBAR_COMMAND_FIELDS = (
    "exec",
    "exec-if",
    "on-click",
    "on-click-middle",
    "on-click-right",
    "on-click-backward",
    "on-click-forward",
    "on-scroll-up",
    "on-scroll-down",
    "on-update",
    "on-double-click",
)


def _resolve_waybar_commands(config: dict[str, Any], binary: str) -> None:
    """Point every `halcyon ...` command at the binary by absolute path.

    Waybar runs these through /bin/sh with whatever PATH its unit
    inherited, and a systemd user session frequently does not have
    ~/.local/bin on it. A bare `halcyon` then fails silently — the button
    is there, it just does nothing, which is exactly how it was reported.
    The keybind renderer already resolves the path for the same reason;
    this is the other half of it.
    """
    if binary == "halcyon":
        # Nothing better was found, so leave the commands alone rather
        # than baking in a path that does not exist.
        return

    def rewrite(command: str) -> str:
        if command == "halcyon":
            return binary
        if command.startswith("halcyon "):
            return binary + command[len("halcyon"):]
        return command

    for key, module in config.items():
        if not isinstance(module, dict):
            continue
        for field in _WAYBAR_COMMAND_FIELDS:
            value = module.get(field)
            if isinstance(value, str):
                module[field] = rewrite(value)
        # `menu-actions` maps a menu entry to a command.
        actions = module.get("menu-actions")
        if isinstance(actions, dict):
            module["menu-actions"] = {
                name: rewrite(cmd) if isinstance(cmd, str) else cmd
                for name, cmd in actions.items()
            }


_WAYBAR_BUILTIN = {
    "battery", "backlight", "bluetooth", "clock", "cpu", "disk", "idle_inhibitor",
    "memory", "mpris", "network", "privacy", "pulseaudio", "temperature", "tray",
    "power-profiles-daemon", "keyboard-state", "user", "load",
}


# ── hyprlock and hypridle ──────────────────────────────────────────────
#
# Both are separate programs from the compositor and still use hyprlang,
# so they get their own small generated includes rather than Lua.


def render_hyprlock_colors(tokens: dict[str, Any]) -> str:
    colors = tokens["color"]
    typography = tokens["typography"]

    def hyprlang(name: str) -> str:
        raw = colors[name].lstrip("#")
        if len(raw) == 8:
            return f"rgba({raw[2:]}{raw[0:2]})"
        return f"rgba({raw}ff)"

    def bare(name: str) -> str:
        """The six-digit form, for Pango markup inside hyprlock labels."""
        return colors[name].lstrip("#")[2:]

    lines = [f"# {line}" for line in BANNER.splitlines()]
    lines.append("")
    for variable, token in (
        ("hal_text", "text"),
        ("hal_text_secondary", "textSecondary"),
        ("hal_text_tertiary", "textTertiary"),
        ("hal_surface", "surface"),
        ("hal_surface_raised", "surfaceRaised"),
        ("hal_border", "glassBorderStrong"),
        ("hal_accent", "accent"),
        ("hal_danger", "danger"),
        ("hal_warning", "warning"),
        ("hal_shadow", "shadow"),
    ):
        lines.append(f"${variable} = {hyprlang(token)}")

    for variable, token in (
        ("hal_text_rgb", "text"),
        ("hal_text_tertiary_rgb", "textTertiary"),
        ("hal_danger_rgb", "danger"),
        ("hal_accent_rgb", "accent"),
    ):
        lines.append(f"${variable} = {bare(token)}")

    lines.append(f"$hal_font_ui = {typography['family']}")
    lines.append(f"$hal_font_mono = {typography['mono']}")
    lines.append("")
    return "\n".join(lines)


def render_hypridle_timeouts(settings: dict[str, Any]) -> str:
    """Idle timeouts for the current power source.

    hypridle has no notion of "different timeouts on battery", so the
    active set is written here and rewritten by `halcyon power watch`
    when the machine is plugged in or unplugged.
    """
    from . import power as power_module

    idle = settings.get("power", {}).get("idle", {})
    battery = power_module.battery_state()
    on_battery = battery.present and not battery.plugged
    prefix = "battery" if on_battery else "ac"

    def seconds(name: str, fallback: int) -> int:
        return int(idle.get(f"{prefix}{name}", fallback))

    lines = [f"# {line}" for line in BANNER.splitlines()]
    lines.append(f"# Active set: {'on battery' if on_battery else 'on AC power'}.")
    lines.append("")

    if not idle.get("enabled", True):
        lines.append("# Idle handling is switched off in Settings → Battery.")
        lines.append("")
        return "\n".join(lines)

    steps = [
        (seconds("DimSeconds", 600), "halcyon backlight 15", "halcyon backlight 100"),
        (
            seconds("ScreenOffSeconds", 900),
            "hyprctl dispatch 'hl.dsp.dpms(\"off\")'",
            "hyprctl dispatch 'hl.dsp.dpms(\"on\")'",
        ),
        (seconds("LockSeconds", 1200), "loginctl lock-session", ""),
        (seconds("SuspendSeconds", 0), "systemctl suspend", ""),
    ]

    for timeout, on_timeout, on_resume in steps:
        if timeout <= 0:
            continue
        lines.append("listener {")
        lines.append(f"    timeout = {timeout}")
        lines.append(f"    on-timeout = {on_timeout}")
        if on_resume:
            lines.append(f"    on-resume = {on_resume}")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


# ── Orchestration ──────────────────────────────────────────────────────


def write_all(
    tokens: dict[str, Any],
    settings: dict[str, Any],
    catalog: dict[str, Any],
    waybar_base: dict[str, Any],
    environment: dict[str, str],
    *,
    outputs: Iterable[str] | None = None,
) -> list[str]:
    """Write every generated artefact; returns the paths written."""
    wanted = set(outputs) if outputs else None
    written: list[str] = []

    def emit(name: str, path: os.PathLike[str] | str, content: str) -> None:
        if wanted is not None and name not in wanted:
            return
        write_atomic(path, content)
        written.append(str(path))

    emit("theme", paths.THEME_JSON, render_theme_json(tokens))
    emit("waybar-css", paths.WAYBAR_CSS, render_waybar_css(tokens))
    emit("hypr-theme", paths.HYPR_THEME_LUA, render_hypr_theme_lua(tokens, settings))
    emit("hypr-animations", paths.HYPR_ANIM_LUA, render_hypr_animations_lua(tokens))
    emit(
        "hypr-keybinds",
        paths.GENERATED_DIR / "hypr-keybinds.lua",
        render_hypr_keybinds_lua(settings, catalog),
    )
    emit(
        "hypr-runtime",
        paths.GENERATED_DIR / "hypr-runtime.lua",
        render_hypr_runtime_lua(settings, tokens, environment),
    )
    emit(
        "waybar-config",
        paths.GENERATED_DIR / "waybar-config.jsonc",
        render_waybar_config(settings, tokens, waybar_base),
    )
    emit(
        "hyprlock",
        paths.GENERATED_DIR / "hyprlock-colors.conf",
        render_hyprlock_colors(tokens),
    )
    emit(
        "hypridle",
        paths.GENERATED_DIR / "hypridle-timeouts.conf",
        render_hypridle_timeouts(settings),
    )
    return written
